config/routes.rb
Rails.application.routes.draw do
  # get 'users/:id', to: 'users#show'
  # get 'users/:id/edit', to: 'users#edit'
  # patch 'users/:id' , to: 'users#update'
  get 'dashboard', to: 'dashboard#index'
  get 'profile', to: 'profile#index'
  # get 'appointments/new', to: 'appointments#new'
  # post 'appointments/create', to: 'appointments#create'
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update]
  resources :pets do
    resources :appointments, only: [:new, :create]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :pet
end

app/models/pet.rb
class Pet < ApplicationRecord
  has_many :appointments
  belongs_to :user
  has_one_attached :photo

  def avatar_url
    photo.present? ? photo.key : 'default'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def avatar_url
    photo.present? ? photo.key : 'default'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :store_location
  before_action :authenticate_user!
  # before_action :store_user_location!, if: :storable_location?
  
  # def after_sign_in_path_for(resource)
  #   if session[:form_data].present?
  #     dashboard_path
  #   end
  # end

  def after_sign_in_path_for(resource)
    if session[:pet_id]
      pet_path(session[:pet_id])      
    else
      root_path
    end
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :create

  def new
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.new
    # if session[:form_data]
    #   params = session[:form_data]
    #   session[:form_data] = nil
    #   @appointment = Appointment.new(appointment_params)
    #   raise
    # end
  end

  def create
    if current_user.nil?
      # session[:form_data] = params
      session[:pet_id] = params[:pet_id]
      redirect_to new_user_session_path, notice: "You must be signed in to access this page." 
    else
      @appointment = Appointment.new(appointment_params)
      @pet = Pet.find(params[:pet_id])
      @appointment.pet = @pet
      @appointment.user = current_user
      if @appointment.save
        redirect_to dashboard_path
      else
        render :new
      end
    end
  end

  private

  def appointment_params
    params
    .require(:appointment)
    .permit(:pet_id, :start_date_time, :end_date_time)
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index
    @appointments = current_user.appointments
    @pets = current_user.pets
    render :index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @pet = Pet.new
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  skip_before_action :authenticate_user!, only: :show

  def index
    if params[:query1].present? && params[:query2].present?
      @pets = Pet.where("species ILIKE ? AND location ILIKE ?", "%#{params[:query1]}%", "%#{params[:query2]}%")
    elsif
      params[:query1].present?
      @pets = Pet.where("species ILIKE ?", "%#{params[:query1]}%")
    elsif
      params[:query2].present?
      @pets = Pet.where("location ILIKE ?", "%#{params[:query2]}%")
    else  
      @pets = Pet.all
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @appointment = Appointment.new
  end

  def new
    @pet = Pet.new
    @pet.user = current_user
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to @pet, notice: 'Your pet was successfully created!'
    else
      render :new
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
  end

  private

  def pet_params
    params
    .require(:pet)
    .permit(:name, :user_id, :species, :availability, :pet_ability, :description, :photo, :location)
  end


end

app/controllers/pets_controllers.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new
    if @pet.save
      redirect_to @pet, notice: 'Your pet was successfully created!'
    else
      render :new
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = current_user
    @pets = current_user.pets
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @pets = @user.pets
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user == current_user
      @user.update(user_params)
      redirect_to user_path(@user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :bio, :username, :photo)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<%= simple_form_for([@pet, @appointment]) do |f| %>
  <%= f.label :start_date_time %>
  <%= f.text_field :start_date_time %>
  <%= f.label :end_date_time %>
  <%= f.text_field :end_date_time %>
  <%= f.submit %>
<% end %>

app/views/dashboard/index.html.erb
<div class="container container-large">

  <div class="container justify-content-center my-3">
    <div class="row d-flex align-items-center flex-column my-4">

      <div>
        <h1>My dashboard</h1>
      </div>

      <br>

        <h4>Success!</h4>
        <br>
        <%= cl_image_tag @appointments.last.pet.avatar_url, crop: :fill %>
        <p>
        <h3>My next appointment</h3>
        <% if @appointments %>
          <p><strong><%= @appointments.last.pet.name %></strong></p>
          <p><strong>From: </strong><%= @appointments.last.start_date_time.strftime("%A, %d %b %Y @ %l:%M %p") %>
          <br>
          <strong>To: </strong><%= @appointments.last.end_date_time.strftime("%A, %d %b %Y @ %l:%M %p") %></p>
        <% end %>
        <p>You are well on your way to meeting your new PetPal! </p>

        <p>You'll be spending time with <strong><%= @appointments.last.pet.name %></strong> next. It's going to be awesome.</p>
        <hr>
        <p class="mb-0">Make sure to check in with the pet's owner about any special care instructions.</p>

      <hr>

    </div>
  </div>

  <div class="container">
    <div class="d-flex justify-content-around">

      <div class="flex-item">
        <h3>Past appointments</h3>
        <% if @appointments %>
          <% @appointments.each do |appointment| %>
            <% unless @appointments.last == appointment %>
              <%= cl_image_tag appointment.pet.avatar_url, height: 225, width: 300, crop: :fill %>
              <p><strong><%= appointment.pet.name %></strong></p>
              <p>From: <%= @appointments.last.start_date_time.strftime("%A, %d %b %Y @ %l:%M %p") %>
              <br>
              To: <%= @appointments.last.end_date_time.strftime("%A, %d %b %Y @ %l:%M %p") %></p>
              <hr>
              <% end %>
          <% end %>
        <% end %>
      </div>

    </div>


  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petpal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'shared/flashes' %>
        <%= render 'shared/navbar' %>
        <%= yield %>
        <%= render 'shared/footer' %>
      </div>
    </div>


  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex align-items-center justify-content-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path("landing-bg.jpg") %>);">
  <div class="container">
    <div class="row justify-content-center pb-3">
      <h1>Find your furry pal for a weekend or just for a walk</h1>
      <div class="search-inline">
        <form action="/pets" class="form-inline justify-content-center">
          <div class="input-group mb-2 mr-sm-2">
            <%= form_tag pets_path, method: :get do %>
            <div class="label-home">
              <%= text_field_tag :query1,
              params[:query1],
              class: "form-control",
              placeholder: "Search by species" %>
            </div>
            <div class="label-home">
              <%= text_field_tag :query2,
              params[:query2],
              class: "form-control",
              placeholder: "Search by location" %>
            </div>
            <%# <button type="submit" class="btn btn-warning mb-2">Find Your PetPal!</button> %>
            <%= submit_tag "Find Your PetPal!", class: "btn btn-warning mb-2" %>
            <% end %>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div id="scrollhint">
    <a href="#" class="arrow down" onclick="scrollDown(event)">Scrolldown</a>
  </div>
</div>

<div class="container">



<div class="container">
  <div class="row justify-content-center">

    <h2>How does it work?</h2>
    <br>

    <div class="card-container">

      <div class="row info-card">
        <div class="col-5 img-show">
          <%= image_tag("landing-1.jpg", size: "300x250") %>
        </div>
        <div class="col-7">
          <h3>Find your furry PetPal</h3>
          <p>Need a break from the chaos that is life? Don't get stuck between a rock and a hard place. Browse now and find your next animal adventure - dog 🐶 or dragon 🐉 , hamster 🐹 or hare 🐰, make your day much easier to bear 🧸.</p>
        </div>
        <!-- </div> -->
      </div>

      <div class="row info-card">
        <div class="col-9 img-show">
          <h3>
            <blink>Book your PetPal</blink>
          </h3>
          <p>Browse different pets, read about their incredible capabilities, learn about their owners, and book your dates now - imagine your afternoon coffee ☕ today with an extra cuddle 🦁.</p>
        </div>
        <div class="col-3">
          <%= image_tag("landing-2.jpg", size: "350x250") %>
        </div>
      </div>

      <div class="row info-card">
        <div class="col-5 img-show" >
          <%= image_tag("landing-3.jpg", size: "250x300") %>
        </div>
        <div class="col-7">
          <h3>Have loads of fun!</h3>
          <p>Discover your next lover and friend and go on a magic carpet ride - your new PetPal will show you the world and open your eyes, you'll see that the possibilities are endless!</p>
        </div>
      </div>

    </div>
  </div>
</div>
<br>



<!-- Start adding reviews  -->


<div class="container">
  <div class="row justify-content-center">
    <h2>Connect to a Worldwide Community of Pet Lovers </h2>
  </div>
    <ul class="hash-list cols-3 cols-1-xs pad-30-all align-center text-sm">
        <li>
          <img src="https://www.bootdey.com/img/Content/avatar/avatar3.png" class="wpx-100 img-round mgb-20"/>
          <p class="fs-110 font-cond-l" contenteditable="false">"Running with Mingo in the park was such a great way to distract myself from the pain that is exercising, still don't know if I was running with him or away from him, but all good."</p>
          <h5 class="font-cond mgb-5 fg-text-d fs-130" contenteditable="false"><strong>Exhilarating experience!</strong></h5>
            <a title="" href="#">Carli</a>
                <i>from Gdansk, Poland</i>
        </li>
        <li>
          <img src="https://bootdey.com/img/Content/avatar/avatar4.png" class="wpx-100 img-round mgb-20"/>
          <p class="fs-110 font-cond-l" contenteditable="false">"Never knew dragons existed until Ringo took me for a little aerial ride above my neighborhood, we even spied on the neighbors and almost started a fire!"</p>
          <h5 class="font-cond mgb-5 fg-text-d fs-130" contenteditable="false"><strong>Absolutely loved it!</strong></h5>
             <a title="" href="#">Ken</a>
                <i>from Malibu, California</i>
        </li>
        <li>
          <img src="https://www.bootdey.com/img/Content/avatar/avatar2.png" class="wpx-100 img-round mgb-20"/>
          <p class="fs-110 font-cond-l" contenteditable="false">"Pure, blood pumping adrenaline - Bingo the bear even left me a small present resembling a bitemark, I bet he misses me already."</p>
          <h5 class="font-cond mgb-5 fg-text-d fs-130" contenteditable="false"><strong>Highly recommend!</strong></h5>
              <a title="" href="#">Sam</a>
                <i>from Vienna, Austria</i>
        </li>
      </ul>
</div>


<!-- End adding reviews -->


<!-- Start JS script -->

<script>

toggleItem = function(){
    var el = document.getElementsByTagName('blink')[0];
    if (el.style.display === 'block') {
        el.style.display = 'none';
    } else {
        el.style.display = 'block';
    }
}

setInterval(toggleItem, 1000);

</script>


<!-- end JS script -->


<script>
  function scrollDown(e) {
    e.preventDefault()
    document.querySelector("div.container:nth-child(3)").scrollIntoView({behavior: "smooth"});
  }
</script>

app/views/pets/index.html.erb
<div class="container">

  <div class="row justify-content-center mt-4">
     <h1>All My PetPals</h1>
  </div>


  <div id="cards-container">
    <div class="card-columns">
      <% @pets.each do |pet| %>
        <%= link_to pet_path(pet), style: "color: black; text-decoration: none" do %>
        <div class="card" style="width: 350px;">
          <div class="card-trip">
          <%= cl_image_tag pet.avatar_url, height: 225, width: 350, crop: :fill %>
            <div class="card-trip-infos">
              <div>
                <h5><%= pet.name %></h5>
                <p><%= pet.description %></p>
              </div>
              <%= link_to (cl_image_tag pet.user.avatar_url, class: "avatar-bordered card-trip-user"), user_path(pet.user_id) %>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container p-4 mb-5 mt-5 add-pet-form opacity">
  <h2>Add your Pet</h2>
    <%= simple_form_for [@pet] do |f| %>
    <%= f.input :name, label: "Name of my PetPal", :placeholder => 'Pingo' %>
    <%= f.input :description, :placeholder => 'Why your PetPal is the best?'%>
    <%= f.input :availability %>
    <%= f.input :species, id: "no-margin", :prompt => 'Dog / Cat / Snake', collection: ["dog", "dragon", "cat", "lion", "hamster", "lizard", "anteater", "horse", "cactus"] %>
    <%= f.input :pet_ability, label: "My pet is available for 👇", :placeholder => 'Pingo is available for morning walks every day!' %>
    <%= f.input :location, :prompt => 'Berlin', id: "no-margin", collection: ["Aachen", "Augsburg", "Berlin", "Bonn", "Braunscheig", "Bremen", "Chemnitz", "Dortmund", "Dresden", "Düsseldorf", "Erfurt", "Frankfurt", "Göttingen", "Hamburg", "Hannover", "Karlsruhe", "Kiel", "Köln", "Leipzig", "Mannheim", "Münich", "Nürnberg", "Stuttgart", "Wuppertal"] %>
    <br>
    <%= f.input :photo, as: :file %>
    <br>
    <%= f.submit 'Add Pet', class: 'btn btn-add btn-block' %>
    <% end %>
    <hr>
    <%= link_to  "Back to all my PetPals", pets_path, class: "btn btn-outline-secondary btn-block"%>
</div>

app/views/pets/show.html.erb
<div class="container">

   <div class="row mt-5">
    <div class="col-xl-6">
      <%= cl_image_tag @pet.avatar_url,:class=>"img-show", height: 400, width: 550, crop: :fill %>
    </div>
       <div class="col ml-3">
          <h1>YOYO I’m <%= @pet.name  %>!</h1>
          <h3>Look at what we can do together:</h3>
          <div class="what-we-can-do">
             <p>👋 <%= @pet.pet_ability %> </p>
          </div>
          <div class="pet-owner">  
          <%= link_to (cl_image_tag @pet.user.avatar_url, class: "avatar"), user_path(@pet.user_id) %>
          
          <p>👈 This is <%= @pet.name %>'s owner! Check the profile!</p>
          </div>
          <div class="appointment-container">
            <!-- <p>🕜  When do you want to meet me?</p> -->
              <%= simple_form_for([@pet, @appointment]) do |f| %>
                <%= f.label :start_date_time %>
                <%= f.text_field :start_date_time %>
                <%= f.label :end_date_time %>
                <%= f.text_field :end_date_time %>
                <button type="submit" id="btn-book" class="btn btn-warning mb-2 btn-book text-white"><%= f.button :submit,"Book #{ @pet.name } "%></button>
              <% end %>
            </div>
        </div>
  </div>

  <script>
    const start_date = flatpickr('#appointment_start_date_time', {
      minDate: "today",
      enableTime: true,
      dateFormat: "F j, Y H:i",
    })
    const end_date = flatpickr('#appointment_end_date_time', {
      enableTime: true,
      dateFormat: "F j, Y H:i",
    })
    start_date._input.addEventListener('change', e => end_date.set('minDate', start_date.selectedDates[0]))
  </script>

  <div class="row description justify-content-center">
    <div class="col-xl-12 text-center">
      <h2>A bit about me</h2>
      <p><%= @pet.description %></p>
    </div>
  </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer align-items-center justify-content-center">
  <p>This site was designed and created with ❤️ by the best team in Berlin, August 2020</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://static.thenounproject.com/png/53200-200.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container pt-5">
  <h2>Edit your profile</h2>
    <%= simple_form_for [@user] do |f| %>
    <%= f.input :username %>
    <%= f.input :bio %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Modify', class: 'btn btn-primary' %>
    <% end %>
    <hr>
    <%= link_to "Back", user_path, class: "btn btn-primary"%>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-5">
      <h2>User profile</h2>

      <div class="card-container d-flex">
       <div class="card profile-card">
          <%= cl_image_tag @user.avatar_url,:class=>"card-img-top avatar-profile", crop: :fill %>
          <div class="card-body">
            <h5 class="card-title"><%= @user.username %></h5>
            <p class="card-text"><%= @user.bio %></p>
            <% if current_user == @user %>

            <div class="btn btn-warning btn-sm mb-2">
              <%= link_to 'Edit profile', edit_user_path, class: "link-color" %>
            </div>
            <div class="btn btn-warning btn-sm">
              <%= link_to 'Add a pet', new_pet_path, class: "link-color" %>
            </div>

            <% end %>

          </div>
        </div>

      </div>

      <div class="card-container d-flex">
       <div class="card profile-card">
          <div class="card-body">
            <h5 class="card-title"><%= @user.username %>, you have reviews!</h5>
            <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
            <p> I went to <%= @user.username %>'s place and had a nice walk with his pet! It was lovely and now I want to have one too! </p>
          </div>
        </div>

      </div>

    </div>


    <div class="col-7">
      <div>
        <h2>PetPals owned by <%= @user.username %></h2>
        <p> </p>
      </div>
      <div class="card-columns">
        <% @pets.each do |pet| %>
          <%= link_to pet_path(pet), style: "color: black; text-decoration: none" do %>

            <div class="card" style="width: 300px;">
              <%= cl_image_tag pet.avatar_url, height: 225, width: 300, crop: :fill %>
              <div class="card-body">
                <h5 class="card-title"><%= pet.name %></h5>
                <p class="card-text"><%= pet.description %></p>
                <% if current_user == @user %>
                  <a href="#" class="btn btn-warning btn-sm">Edit PetPal</a>
                  <div class="btn btn-warning btn-sm">
                    <%= link_to 'Delete PetPal', pet_path(pet), class: "link-color", method: :delete, data: { confirm: "Are you sure you want to delete this PetPal?"} %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>